#!/bin/bash
echo "------------DUMP BASE FILMES------------"
/var/www/arquivos-dev/mysql/dump/./run.sh > /dev/null
echo "------------COPIANDO ARQUIVOS DE CONFIGURACAO------------"
cp ~/.gitconfig /var/www/arquivos-dev/.gitconfig.example
echo "------------COMPACTANDO BACKUP------------"
pastas_origem="/var/www/ /home/cayque/Documentos/backups/"

destino="/media/cayque/CAYQUE_1TB/BKP_PC10"

data=$(date +%Y-%m-%d)
hostname=$(hostname -s)
arquivo_final="$hostname"_"$data.tgz"

tar czf $destino/$arquivo_final $pastas_origem

# Busca todos os arquivos de backup e exclui o mais velho, mantendo sempre os tres mais novos
ls -1 $destino/$hostname*.tgz | sort -r | tail -n +4 | xargs rm > /dev/null 2>&1

ls -lh $destino

echo "------------FIM------------"