version: '3'
services:
  db:
    container_name: mysql-5.7
    build: .
    restart: always
    env_file:
      - ./.env
    volumes:
      - "/var/dados/mysql:/var/lib/mysql"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 3306:3306